### ISSUE TITLE
Scrollbars of both panels are not independet

### ISSUE THREAD

**Issue by barretodavid** [rangle/batarangle#218]
Both panels should have the height of it container and show a scrollbar if grows bigger. Currently, the right container is not displaying an internal scrollbar and when it grows bigger than the viewport, a "main" scrollbar is shown that moves both panels.

**Comment by vanessayuenn** [comment]
hey @barretodavid could you please let us know which version of angular2/batarangle you're using, and if possible, a screenshot of the scrollbar issue you're experiencing?

**Comment by barretodavid** [comment]
Sure. I'm using angular2-beta8 and batarangle 0.0.2

<img width="1132" alt="screen shot 2016-03-23 at 12 48 25 pm" src="https://cloud.githubusercontent.com/assets/2279046/13993173/9ec4ab3c-f0f5-11e5-90ae-7ff4193f6dd4.png">

**Comment by vanessayuenn** [comment]
cool thanks! @barretodavid this issue is fixed with the latest build :)

**Comment by barretodavid** [comment]
Where should I get the latest build? I just went to batarangle.io, hit the install button, drag & drop to my extensions in chrome and I still have the same 0.0.2 version with the same issue. Do I need to do the build myself from source?

**Comment by mobinni** [comment]
Easiest would be to pull the repo and build it yourself indeed.

**Comment by barretodavid** [comment]
Building from repo fix it, thanks
